In [7]:
%load_ext autoreload

# Examen

**Nombre:** Alexis Bautista  
**Fecha de Entrega:** 23 de enero de 2025  
**Paralelo:** GR1CC  
**Enlace de GitHub:** https://github.com/alexis-bautista/Participacion-11-12-MN/blob/main/determinante.ipynb

## Determinante

In [8]:
%autoreload 2
from src import (
    eliminacion_gaussiana,
    descomposicion_LU,
    resolver_LU,
    matriz_aumentada,
    separar_m_aumentada,
)


# ####################################################################
def calc_determinante(A: list[list[float]]) -> float:
    """Función que calcula el determinante usando el método...
    [Descomposición LU, eliminación gaussiana, Gauss-Jordan, Gauss-Jacobi o Gauss-Seidel]

    ## Parameters
    ``A``: Matriz cuadrada de tamaño n x n

    ## Return
    ``detA``: Determinante de la matriz A

    """
    # completar
    return

# Ejercicio 1

In [9]:
A1 = [
    [-4, 2, -4, -4, 1, 2, 5, 3, 5, 1],
    [1, 0, 4, 3, 0, -2, 3, 0, 1, 5],
    [5, 5, -4, 5, -4, 2, 2, 2, 4, 4],
    [-1, 3, 4, -1, -4, 0, 5, 0, 0, 5],
    [4, 1, 4, 2, 0, 0, 3, -1, 0, 2],
    [2, -2, 1, -1, -2, -3, 2, -2, 4, -1],
    [3, -2, -3, -2, -1, -3, 5, -1, 5, 0],
    [3, 4, -3, 3, -2, 2, -4, -4, 1, 5],
    [-4, 0, 3, 3, -3, -2, -2, 0, 5, -4],
    [-2, 4, 4, -2, -1, 1, 5, -1, 3, -3],
]
calc_determinante(A1)

# Ejercicio 2

In [10]:
A2 = [
    [2, 2, 4, 5, -2, -3, 2, -2],
    [-1, -1, 3, 2, 1, 1, -4, 4],
    [2, 5, -3, -3, -2, 2, 5, 3],
    [-2, -4, 0, 1, -1, 5, -4, -1],
    [1, -2, -1, 5, 5, 2, 1, -2],
    [5, 4, 0, 3, 4, -1, -3, -2],
    [4, -4, 1, 2, 3, 3, -1, 3],
    [-2, 1, -3, 0, 5, 4, 4, -4],
]
calc_determinante(A2)

# Modificaciones

Conocemos que al triangular una matriz mediante eliminación gaussiana, el determinante es el producto de los elementos de la diagonal de la matriz triangular superior. Por ello para calcular el determinante de la matriz A usamos la matriz ampliada y la eliminacion gaussiana. Además, se debe tener en cuenta si hubo intercambios de filas, ya que cada intercambio cambia el signo del determinante.

In [45]:
from src import eliminacion_gaussiana, matriz_aumentada
import numpy as np

def calc_determinante(A: list[list[float]]) -> float:
    """Función que calcula el determinante usando el método de eliminación gaussiana.

    ## Parameters
    ``A``: Matriz cuadrada de tamaño n x n

    ## Return
    ``detA``: Determinante de la matriz A

    """
    
    A = np.array(A, dtype=float)
    n = A.shape[0]

    # Comprobamos que la matriz sea cuadrada
    assert A.shape[0] == A.shape[1], "La matriz A debe ser cuadrada."

    # Crear una columna de ceros para podeer crear la matriz aumentada
    b = np.zeros(n)

    # Creamos la matriz aumentada
    Ab = matriz_aumentada(A, b)

    # Aplicamos eliminación gaussiana
    eliminacion_gaussiana(Ab)
    
    # Multiplicamos los elementos diagonales para obtener el determinante
    detA = 1
    for i in range(n):
        detA *= Ab[i, i]
        
    #consideramos los cambios de signo si se realizaron intercambios de filas
    signos = 1
    for i in range(n):
        if Ab[i, i] < 0:
            signos *= -1
    detA = detA * signos

    print ("\n El determinante de la matriz es: ", detA)
    
    #return detA


In [46]:
calc_determinante(A1)

[01-23 19:23:49][INFO] 
[[  1.   0.   4.   3.   0.  -2.   3.   0.   1.   5.   0.]
 [  0.   2.  12.   8.   1.  -6.  17.   3.   9.  21.   0.]
 [  0.   5. -24. -10.  -4.  12. -13.   2.  -1. -21.   0.]
 [  0.   3.   8.   2.  -4.  -2.   8.   0.   1.  10.   0.]
 [  0.   1. -12. -10.   0.   8.  -9.  -1.  -4. -18.   0.]
 [  0.  -2.  -7.  -7.  -2.   1.  -4.  -2.   2. -11.   0.]
 [  0.  -2. -15. -11.  -1.   3.  -4.  -1.   2. -15.   0.]
 [  0.   4. -15.  -6.  -2.   8. -13.  -4.  -2. -10.   0.]
 [  0.   0.  19.  15.  -3. -10.  10.   0.   9.  16.   0.]
 [  0.   4.  12.   4.  -1.  -3.  11.  -1.   5.   7.   0.]]
[01-23 19:23:49][INFO] 
[[  1.   0.   4.   3.   0.  -2.   3.   0.   1.   5.   0.]
 [  0.   1. -12. -10.   0.   8.  -9.  -1.  -4. -18.   0.]
 [  0.   0.  36.  40.  -4. -28.  32.   7.  19.  69.   0.]
 [  0.   0.  44.  32.  -4. -26.  35.   3.  13.  64.   0.]
 [  0.   0.  36.  28.   1. -22.  35.   5.  17.  57.   0.]
 [  0.   0. -31. -27.  -2.  17. -22.  -4.  -6. -47.   0.]
 [  0.   0. -39. -31.  

Luego de aplicar la eliminacion gaussiana y multiplicar los elementos de la diagonal obtuvimo que el determinante de la matriz $A_1$ es 9912776 lo que quiere decir que el sistema de ecuaciones tiene una solucion unica

In [47]:
calc_determinante(A2)

[01-23 19:25:43][INFO] 
[[ -1.  -1.   3.   2.   1.   1.  -4.   4.   0.]
 [  0.   0.  10.   9.   0.  -1.  -6.   6.   0.]
 [  0.   3.   3.   1.   0.   4.  -3.  11.   0.]
 [  0.  -2.  -6.  -3.  -3.   3.   4.  -9.   0.]
 [  0.  -3.   2.   7.   6.   3.  -3.   2.   0.]
 [  0.  -1.  15.  13.   9.   4. -23.  18.   0.]
 [  0.  -8.  13.  10.   7.   7. -17.  19.   0.]
 [  0.   3.  -9.  -4.   3.   2.  12. -12.   0.]]
[01-23 19:25:43][INFO] 
[[  -1.   -1.    3.    2.    1.    1.   -4.    4.    0.]
 [   0.   -1.   15.   13.    9.    4.  -23.   18.    0.]
 [   0.    0.   48.   40.   27.   16.  -72.   65.    0.]
 [   0.    0.  -36.  -29.  -21.   -5.   50.  -45.    0.]
 [   0.    0.  -43.  -32.  -21.   -9.   66.  -52.    0.]
 [   0.    0.   10.    9.    0.   -1.   -6.    6.    0.]
 [   0.    0. -107.  -94.  -65.  -25.  167. -125.    0.]
 [   0.    0.   36.   35.   30.   14.  -57.   42.    0.]]
[01-23 19:25:43][INFO] 
[[ -1.   -1.    3.    2.    1.    1.   -4.    4.    0. ]
 [  0.   -1.   15.   13.    9

Luego de aplicar la eliminacion gaussiana y multiplicar los elementos de la diagonal obtuvimo que el determinante de la matriz $A_2$ es 2341546 lo que quiere decir que el sistema de ecuaciones tiene una solucion unica